name: java-cicd-pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: temurin
          cache: maven

      - name: Build
        run: mvn clean package -DskipTests

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: temurin
          cache: maven

      - name: Run Unit Tests
        run: mvn test

  code-analysis:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: temurin
          cache: maven

      # PMD
      - name: Run PMD
        run: mvn pmd:pmd

      # SpotBugs
      - name: Run SpotBugs
        run: mvn spotbugs:check
  sast:
    runs-on: ubuntu-latest
    needs: code-analysis

    steps:
    - uses: actions/checkout@v7

    - uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: temurin
        cache: maven

    - name: Resolve dependencies
      run: mvn dependency:resolve

    - name: Run Trivy
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: fs
        scan-ref: .
        severity: HIGH,CRITICAL
        format: table
        exit-code: '0'

  docker:
    runs-on: ubuntu-latest
    needs: sast

    steps:
      - uses: actions/checkout@v7

      - name: Login DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v4

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and Push Image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{github.run_id}}

  dast:
    runs-on: ubuntu-latest
    needs: docker

    steps:
      - uses: actions/checkout@v7

      - name: Run Container
        run: docker run -d -p 8080:9090 ${{ secrets.DOCKER_USERNAME }}/${{github.run_id}} --name spring-app

      - name: Wait for application
        run: |
          for i in {1..30}; do
            if curl -f http://localhost:8080; then
            exit 0
            fi
          sleep 5
          done
          docker logs spring-app
          exit 1

      - name: Run OWASP ZAP
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: "http://localhost:8080"
          

      

    

  

      
